### ISSUE TITLE
What happens when you pause a Multi-Geo capacity?

### ISSUE THREAD

**Issue by w0ut0** [MicrosoftDocs/powerbi-docs.es-es#10]
Does the data (query cache mainly) stay in the assigned region, or is the workspace assigned back to the shared capacity (and thus to the default region)?

Thank you for the clarification,

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 2e1ae590-933f-bf65-888e-03dbf0ddc252
* Version Independent ID: ae8f54bb-5fdb-a071-528d-169b4b766be6
* Content: [Ondersteuning voor Multi-Geo voor Power BI Premium (preview-versie) - Power BI](https://docs.microsoft.com/nl-nl/power-bi/service-admin-premium-multi-geo)
* Content Source: [powerbi-docs/service-admin-premium-multi-geo.md](https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/blob/live/powerbi-docs/service-admin-premium-multi-geo.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by LisandroSu** [comment]
Hello, @w0ut0 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
