### ISSUE TITLE
Desconexión entre Desktop y Apps/Web

### ISSUE THREAD

**Issue by betomoralesmtz** [MicrosoftDocs/powerbi-docs.es-es#11]
Hola, es la segunda vez que publico mi reporte, entro a la página Web y las aplicaciones y no se actualiza.  Se ve como la versión anterior y además algunas gráficas tienen un símbolo de error.  La primera vez borré el reporte en la página Web y lo volví a cargar, pero no quiero hacer eso cada vez.

Fields that need to be fixed
Something's wrong with one or more fields: (Real) Vol 2018 YTD (UC)
Please try again later or contact support. If you contact support, please provide these details.
Activity ID: 7a854d9a-053c-4933-94c2-6f0789ab4439
Request ID: fa99da22-ca35-454c-3662-4aade9bd4c46
Correlation ID: eb8f2788-469b-9842-7bef-26b545cd53f3
Time: Thu Sep 27 2018 10:13:45 GMT-0500 (Hora de verano central (México))
Version: 13.0.6836.190
Cluster URI: https://wabi-south-central-us-redirect.analysis.windows.net

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ vinculación de problemas de GitHub.*

* ID: 179482da-6009-3602-8e51-c20a42c83b5b
* Version Independent ID: b023c9e5-94e0-4d0c-67ce-465916170c43
* Content: [Solución de problemas de escenarios de actualización - Power BI](https://docs.microsoft.com/es-mx/power-bi/refresh-troubleshooting-refresh-scenarios)
* Content Source: [powerbi-docs/refresh-troubleshooting-refresh-scenarios.md](https://github.com/MicrosoftDocs/powerbi-docs.es-es/blob/live/powerbi-docs/refresh-troubleshooting-refresh-scenarios.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by LisandroSu** [comment]
Hola, @betomoralesmtz : 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
