### ISSUE TITLE
Informes para dispositivos móviles 

### ISSUE THREAD

**Issue by lujano23** [MicrosoftDocs/powerbi-docs.es-es#12]
No se ve reflejado el informe para dispositivos móviles. Me podrían apoyar?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: ef5362a0-2148-3de0-fd60-a3fe5d06fe91
* Version Independent ID: 1967384e-308d-cf6f-ad5f-cde6e5b741b3
* Content: [Publicar desde Power BI Desktop - Power BI](https://docs.microsoft.com/es-es/power-bi/desktop-upload-desktop-files)
* Content Source: [powerbi-docs/desktop-upload-desktop-files.md](https://github.com/MicrosoftDocs/powerbi-docs.es-es/blob/live/powerbi-docs/desktop-upload-desktop-files.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by LisandroSu** [comment]
Hola, @lujano23 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
