### ISSUE TITLE
pregunta

### ISSUE THREAD

**Issue by Bragmont** [MicrosoftDocs/powerbi-docs.es-es#13]
como poder ponerle en la configuración de POWER BI un formato de suma de horas?, es decir, en vez de q me ponga: 1/5/1900 2:21:15 AM, que mejor me ponga: 120:21:15.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: f0509d4c-73e0-1ffe-6e71-965f76ec4e12
* Version Independent ID: d6ea7fca-f40e-5ac3-0d6a-11d072f64fe4
* Content: [Agregados (suma, promedio, máximo, etc.) en las visualizaciones - Power BI](https://docs.microsoft.com/es-es/power-bi/service-aggregates)
* Content Source: [powerbi-docs/service-aggregates.md](https://github.com/MicrosoftDocs/powerbi-docs.es-es/blob/live/powerbi-docs/service-aggregates.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by LisandroSu** [comment]
Hola, @Bragmont : 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
