### ISSUE TITLE
Libreria de datos

### ISSUE THREAD

**Issue by augusmendoza** [MicrosoftDocs/powerbi-docs.es-es#14]
Deberian tener librerias de datos para seguir los mismos ejemplos y hacer mas practico el curso

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 69c7a5b0-75bd-3ba7-1fac-7557b790d511
* Version Independent ID: b89aefeb-6cc8-4874-e514-7a1428611c8c
* Content: [Obtención de datos - Power BI](https://docs.microsoft.com/es-es/power-bi/guided-learning/gettingdata?tutorial-step=7)
* Content Source: [powerbi-docs/guided-learning/gettingdata.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr.es-ES/blob/live-sxs/powerbi-docs/guided-learning/gettingdata.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #398](https://github.com/MicrosoftDocs/powerbi-docs/issues/398) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hola, @augusmendoza :

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/powerbi-docs/issues/398. 
Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
