### ISSUE TITLE
Feedback op DAX introduxctie

### ISSUE THREAD

**Issue by ATSFInfodex** [MicrosoftDocs/powerbi-docs.es-es#15]
De introductie vind ik een goede DAX awareness training. Overzichtelijk aangeboden en de uitwisseling met de studenten gaf extra dimensie

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: bcb9bc55-ac56-d1ab-c465-4e41bfa8f152
* Version Independent ID: 44bd9bb3-5aad-31ac-27b6-53e3c0554960
* Content: [Inleiding tot DAX - Power BI](https://docs.microsoft.com/nl-nl/power-bi/guided-learning/introductiontodax?tutorial-step=7)
* Content Source: [powerbi-docs/guided-learning/introductiontodax.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr.nl-NL/blob/live-sxs/powerbi-docs/guided-learning/introductiontodax.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by LisandroSu** [comment]
Hallo, @ATSFInfodex 

We stellen uw feedback zeer op prijs. Goed om te horen dat uw ervaring met onze documentatie aan de verwachtingen voldoet! 

We hopen dat u ons uw waardevolle feedback blijft geven zodat we uw ervaring kunnen blijven verbeteren. 

Met vriendelijke groet, 
Het team van Microsoft DOCS International
