### ISSUE TITLE
Debo instalar algún Controlador adicional ?

### ISSUE THREAD

**Issue by yonatan-alvarez** [MicrosoftDocs/powerbi-docs.es-es#16]
Hola, Por favor me indican si debo instalar algún Controlador adicional ?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 02b27c75-1cfd-7fdd-33d8-a401fcf2989c
* Version Independent ID: 0bd5b042-8ab5-bca0-64bb-c0c59665f4d8
* Content: [Conectarse a una base de datos de Impala en Power BI Desktop - Power BI](https://docs.microsoft.com/es-es/power-bi/desktop-connect-impala)
* Content Source: [powerbi-docs/desktop-connect-impala.md](https://github.com/MicrosoftDocs/powerbi-docs.es-es/blob/live/powerbi-docs/desktop-connect-impala.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
Hola, @yonatan-alvarez 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
