### ISSUE TITLE
Añadir columna

### ISSUE THREAD

**Issue by aplaza333** [MicrosoftDocs/powerbi-docs.es-es#17]
Hola buenas,

¿Es posible añadir columnas al dataset a una tabla que ya está creada? 

Gracias,

Un saludo

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: f6192675-1fad-3f96-36c7-16a54075a060
* Version Independent ID: 8aa38db1-1768-3588-1517-d0ddd2b10a7d
* Content: [Inserción de datos en un conjunto de datos - Power BI](https://docs.microsoft.com/es-es/power-bi/developer/walkthrough-push-data)
* Content Source: [powerbi-docs/developer/walkthrough-push-data.md](https://github.com/MicrosoftDocs/powerbi-docs.es-es/blob/live/powerbi-docs/developer/walkthrough-push-data.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by CeciAc** [comment]
Hola, @aplaza333 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
