### ISSUE TITLE
pagina niet up-to-date

### ISSUE THREAD

**Issue by Kokkie-continues** [MicrosoftDocs/powerbi-docs.es-es#18]
De vertaling voor januari 2019 ontbreekt nog, zie https://docs.microsoft.com/en-us/power-bi/report-server/changelog

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: ef9c2df3-28df-34d8-bd4e-4209996f7f8d
* Version Independent ID: e5dc42c8-b17a-4e0e-09c5-76124b0ad924
* Content: [Wijzigingenlogboek voor Power BI Report Server - Power BI](https://docs.microsoft.com/nl-nl/power-bi/report-server/changelog)
* Content Source: [powerbi-docs/report-server/changelog.md](https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/blob/live/powerbi-docs/report-server/changelog.md)
* Service: **powerbi**
* GitHub Login: @jtarquino
* Microsoft Alias: **jtarquino**

**Comment by CeciAc** [comment]
Hallo, @Kokkie-continues 
 Hartelijk dank voor uw feedback. 
 We gaan uw opmerkingen bekijken en geven u snel een reactie. 
 Met vriendelijke groet, 
Het team van Microsoft DOCS International

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs.nl-nl #3](https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/issues/3) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hallo, @Kokkie-continues 
We stellen uw feedback zeer op prijs. 
Omdat uw opmerkingen specifiek zijn voor de lokalisatie van de documentatie, hebben we dit probleem doorgestuurd naar de desbetreffende lokalisatieopslagplaats en sluiten we deze kwestie. 
Controleer de status van het probleem hier https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/issues/3
Met vriendelijke groet, 
Het team van Microsoft DOCS International
