### ISSUE TITLE
Yesterday the services worked but today they don't

### ISSUE THREAD

**Issue by Bram62** [MicrosoftDocs/powerbi-docs.es-es#20]
Yesterday I managed to use this service but today all I get is a loading screen

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: c6b5bc04-3e2a-820f-6069-7392a2317108
* Version Independent ID: 43adcf87-006a-a74b-29c8-a7ff1701f13d
* Content: [Verbinding met Salesforce maken via Power BI - Power BI](https://docs.microsoft.com/nl-nl/power-bi/service-connect-to-salesforce)
* Content Source: [powerbi-docs/service-connect-to-salesforce.md](https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/blob/live/powerbi-docs/service-connect-to-salesforce.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by CeciAc** [comment]
Hello, @Bram62 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
