### ISSUE TITLE
Problemas para crear un certificado

### ISSUE THREAD

**Issue by JavierEvaristo** [MicrosoftDocs/powerbi-docs.es-es#22]
En primer lugar, agradecer este post, que considero muy útil para mi autoformación.
Sin embargo, estoy teniendo problemas para la creación e instalación de un certificado
Al escribir el comando: pbiviz --create-cert
Me aparece el siguiente mensaje de error:
error: unknown option `--create-cert'
He buscado en otras páginas y utilizan el mismo comando por lo que no tengo ninguna idea de que puede estar causando este error. ¿Podríais ayudarme?
Muchas gracias

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 5c4bae6e-72e1-e41c-4419-48a56423e81e
* Version Independent ID: 6d864495-b578-2d28-169d-edb5409de943
* Content: [Desarrollo de objetos visuales personalizados de Power BI - Power BI](https://docs.microsoft.com/es-es/power-bi/developer/custom-visual-develop-tutorial#feedback)
* Content Source: [powerbi-docs/developer/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs.es-es/blob/live/powerbi-docs/developer/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @sranins
* Microsoft Alias: **rasala**

**Comment by CeciAc** [comment]
Hola, @JavierEvaristo
Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
