### ISSUE TITLE
Como conectar con un servidor sql no local

### ISSUE THREAD

**Issue by Aligtrrz** [MicrosoftDocs/powerbi-docs.es-es#24]
Aun no logro ver como podría conectarme a un motor sql que se encuentre en un servidor externo, que configuraciones debería hacer para lograrlo?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 58eaf5cf-f2f4-785c-a766-38e1868bf820
* Version Independent ID: 5f8db39f-c5bd-c7ce-5258-c8b47cb83c7f
* Content: [Administrar el origen de datos: SQL - Power BI](https://docs.microsoft.com/es-es/power-bi/service-gateway-enterprise-manage-sql#feedback)
* Content Source: [powerbi-docs/service-gateway-enterprise-manage-sql.md](https://github.com/MicrosoftDocs/powerbi-docs.es-es/blob/live/powerbi-docs/service-gateway-enterprise-manage-sql.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by srvbpigh** [comment]
Hello, @Aligtrrz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @Aligtrrz

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
