### ISSUE TITLE
No funcionan los permisos

### ISSUE THREAD

**Issue by LucasCartisano** [MicrosoftDocs/powerbi-docs.es-es#25]
Edité los permisos siguiendo las instrucciones de la página, tanto a nivel de informe como a nivel de datos figura que el usuario X tiene permiso de lectura, sin embargo al ingresar con este usuario al informe, cada objeto visual dice que contiene datos restringidos

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Uso compartido de informes y paneles de Power BI con compañeros y otros usuarios - Power BI](https://docs.microsoft.com/es-es/power-bi/service-share-dashboards#feedback)
* Content Source: [powerbi-docs/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs.es-es/blob/live/powerbi-docs/service-share-dashboards.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srvbpigh** [comment]
Hello, @LucasCartisano
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #1466](https://github.com/MicrosoftDocs/powerbi-docs/issues/1466) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
Hola, @LucasCartisano : 

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: XXX. 
Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
