### ISSUE TITLE
Problema de sincronización

### ISSUE THREAD

**Issue by fboza1978** [MicrosoftDocs/powerbi-docs.es-es#27]
Por medio de este método, la sincronización de los datos solo se permite cada día, cuando deberia ser cada hora.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 92a1e2f2-6f7a-06ab-77a5-efff8aedabe3
* Version Independent ID: 67d3cd28-51ec-07d9-ed36-840097415f56
* Content: [Usar vínculos de OneDrive para la Empresa en Power BI Desktop - Power BI](https://docs.microsoft.com/es-es/power-bi/desktop-use-onedrive-business-links#feedback)
* Content Source: [powerbi-docs/desktop-use-onedrive-business-links.md](https://github.com/MicrosoftDocs/powerbi-docs.es-es/blob/live/powerbi-docs/desktop-use-onedrive-business-links.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @fboza1978
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @fboza1978

Valoramos enormemente su comentario y estamos haciendo todo lo posible por mejorar su experiencia en docs.microsoft.com. No obstante, necesitamos más información para poder encargarnos de sus comentarios. ¿Puede proporcionar información más detallada y aclarar el comentario?

Atentamente,
Equipo internacional de Microsoft DOCS

**Comment by CeciAc** [comment]
Hola, @fboza1978 

Gracias nuevamente por su comentario.

Lamentablemente, aún nos falta información y no podemos procesar sus comentarios. En este momento, cerraremos este problema de GitHub, pero le animamos a enviar más comentarios en el futuro.

Atentamente,
Equipo internacional de Microsoft DOCS
