### ISSUE TITLE
Duda con discretización de fechas.

### ISSUE THREAD

**Issue by Shibz17** [MicrosoftDocs/powerbi-docs.es-es#28]
Tengo una tabla de calendario que inicia el 02 de enero de 2017 y termina el 03 de enero de 2021. Cuando hago la agrupación por 7 días, para lograr agrupar por semanas (de lunes a domingo), retorna erróneamente el inicio de semana.

Por ejemplo:
Tipo de discretización: "Tamaño de las discretizaciones" = 7 días.
Discreción por 7 días, debería ser del 02 de enero de 2017 al 08 de enero 2017
pero retorna: 01 de enero de 2017 al 07 de enero de 2017.

Otro ejemplo:
Tipo de discretización: "Número de las discretizaciones" = 209. (el número de semanas 

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 7502a07a-7f30-882d-7542-2a194651c421
* Version Independent ID: e3c6e2fd-b672-6858-864c-69026d36c0ae
* Content: [Usar la agrupación y la discretización en Power BI Desktop - Power BI](https://docs.microsoft.com/es-es/power-bi/desktop-grouping-and-binning#feedback)
* Content Source: [powerbi-docs/desktop-grouping-and-binning.md](https://github.com/MicrosoftDocs/powerbi-docs.es-es/blob/live/powerbi-docs/desktop-grouping-and-binning.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by Shibz17** [comment]
Otro ejemplo:
Tipo de discretización: "Número de las discretizaciones" = 209. (el número de semanas que posee la tabla)

Semana 1: 02 de enero de 2017 a 08 de enero 2017. Correcto por el momento, porque paulatinamente comienza a correr el día, y cambie el formato de fecha para que incluya las horas y me di cuenta que hace lo siguiente.
Semana 1: 02 de enero de 2017 0:00:00 al 08 de enero de 2017 23:53:06.
Por lo cual, en 2020 se corren las semanas.

Otro Ejemplo:
Tipo de discretización: "Tamaño de las discretizaciones" = 604800 segundos.
Semana 1: 31 de diciembre de 2016 al 06 de enero de 2017. 

Entonces, ¿Cómo lo puedo hacer para que haga una correcta agrupación por 7 días?

**Comment by Shibz17** [comment]
*Que no sea manual, ya que, entenderán que por el tamaño del archivo sería extremadamente tedioso.

**Comment by srvbpigh** [comment]
Hello, @Shibz17
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #2096](https://github.com/MicrosoftDocs/powerbi-docs/issues/2096) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hola, @Shibz17:  

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original.  

Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/powerbi-docs/issues/2096.  

Apreciamos su contribución a nuestros artículos.   

Atentamente,  
Equipo internacional de Microsoft Docs
