### ISSUE TITLE
chile

### ISSUE THREAD

**Issue by jemariro** [MicrosoftDocs/powerbi-docs.es-es#31]
[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 6a301928-35b6-2b9d-3bbe-0dc48b237b07
* Version Independent ID: 765bad52-68e2-985f-924e-4e7f334b62f0
* Content: [Usar mapas de formas en Power BI Desktop (versión preliminar) - Power BI](https://docs.microsoft.com/es-es/power-bi/visuals/desktop-shape-map)
* Content Source: [powerbi-docs/visuals/desktop-shape-map.md](https://github.com/MicrosoftDocs/powerbi-docs.es-es/blob/live/powerbi-docs/visuals/desktop-shape-map.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **rien**

**Comment by srvbpigh** [comment]
Hello, @jemariro
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hola, @jemariro : 

Valoramos enormemente su comentario y estamos haciendo todo lo posible por mejorar su experiencia en docs.microsoft.com. No obstante, necesitamos más información para poder encargarnos de sus comentarios. ¿Puede proporcionar información más detallada y aclarar el comentario? 

Atentamente, 

Equipo internacional de Microsoft DOCS

**Comment by CeciAc** [comment]
Hola, @jemariro 

Gracias nuevamente por su comentario.

Lamentablemente, aún nos falta información y no podemos procesar sus comentarios. En este momento, cerraremos este problema de GitHub, pero le animamos a enviar más comentarios en el futuro.

Atentamente,
Equipo internacional de Microsoft DOCS
