### ISSUE TITLE
¿Dónde podemos encontrar los ficheros de prueba para seguir sus ejemplos? Gracias.

### ISSUE THREAD

**Issue by PaulaC** [MicrosoftDocs/powerbi-docs.es-es#5]
No consigo acceder a los ficheros para seguir el curso,
muchas gracias, un saludo.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 69c7a5b0-75bd-3ba7-1fac-7557b790d511
* Version Independent ID: b89aefeb-6cc8-4874-e514-7a1428611c8c
* Content: [Obtención de datos - Power BI](https://docs.microsoft.com/es-es/power-bi/guided-learning/gettingdata?tutorial-step=7)
* Content Source: [powerbi-docs/guided-learning/gettingdata.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr.es-ES/blob/live-sxs/powerbi-docs/guided-learning/gettingdata.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by LisandroSu** [comment]
Hola @PaulaC 

Muchas gracias por sus comentarios.

¿Puede proporcionarme la página en la que no encuentra los archivos? La página a la que hace referencia este GitHub Issue no menciana ningún archivo.

Atentamente, 
Equipo internacional de Microsoft Docs

**Comment by LisandroSu** [comment]
Hola @PaulaC 

¿Puede proporcionarme la página en la que no encuentra los archivos? La página a la que hace referencia este GitHub Issue no menciana ningún archivo.

Atentamente,
Equipo internacional de Microsoft Docs

**Comment by CeciAc** [comment]
Hola, @PaulaC

Gracias una vez más por tu comentario.
Lamentablemente, todavía nos falta información y no podemos procesar sus comentarios. Estamos cerrando este problema de GitHub en este momento, pero le recomendamos que envíe más comentarios en el futuro.

Saludos cordiales,
Equipo de Microsoft DOCS International

**Comment by PaulaC** [comment]
Buenos días Cecilia,
Este Github soporta la información correspondiente a un ejemplo de Power
BI. Siguiendo las indicaciones del manual te piden que te descargues la
información del Github al que me refiero, pero una vez has accedido (previo
registro), no hay ninguna información que descargar.
un saludo.

**Comment by PaulaC** [comment]
Ha pasado tanto tiempo y habéis tardado tanto tiempo en responder que ya no
lo recuerdo.
Gracias
un saludo.
