### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by Jasperschiks** [MicrosoftDocs/powerbi-docs.es-es#7]
Is this also coming to android? It's a great feature but only available on iOS

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: a19d0436-4c82-5830-5ad6-3cc8b4281ff5
* Version Independent ID: fc73c232-b9a5-e0db-e013-838d955a22d0
* Content: [Een streepjescode met een iPhone scannen via de mobiele Power BI-app - Power BI](https://docs.microsoft.com/nl-nl/power-bi/mobile-apps-scan-barcode-iphone)
* Content Source: [powerbi-docs/mobile-apps-scan-barcode-iphone.md](https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/blob/live/powerbi-docs/mobile-apps-scan-barcode-iphone.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by LisandroSu** [comment]
Hello, @Jasperschiks 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
