### ISSUE TITLE
Instructor changed to non-native English speaker

### ISSUE THREAD

**Issue by MichaBrans** [MicrosoftDocs/powerbi-docs.es-es#8]
In part 2 of this chapter, the normal instructor has been changed to another instructor with a very heavy non-english accent. What a pitty...

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 49462b9d-81da-e29a-f148-1fd95395a570
* Version Independent ID: 4ce1f7c2-0170-35b5-adca-c92c41fb7fc1
* Content: [Modellen maken - Power BI](https://docs.microsoft.com/nl-nl/power-bi/guided-learning/modeling?tutorial-step=8)
* Content Source: [powerbi-docs/guided-learning/modeling.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr.nl-NL/blob/live-sxs/powerbi-docs/guided-learning/modeling.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by LisandroSu** [comment]
Hello, @MichaBrans 

Your comments are in violation of our code of conduct on https://opensource.microsoft.com/codeofconduct/. 

For this reason, we have to lock and close this issue.

Kind regards,
Microsoft DOCS International Team
