### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by todobien777** [MicrosoftDocs/powerbi-docs.es-es#9]
Es muy interesante la información pero también se debería pensar en dejar subtítulos en español en los videos ya que todo mundo no habla o maneja a la perfeccion el ingles 

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 94b08723-3d20-45e8-1a6e-348c33cb5ff2
* Version Independent ID: a201f1c5-9771-5eff-bac6-85de7058a8b3
* Content: [Introducción - Power BI](https://docs.microsoft.com/es-es/power-bi/guided-learning/gettingstarted?tutorial-step=6)
* Content Source: [powerbi-docs/guided-learning/gettingstarted.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr.es-ES/blob/live-sxs/powerbi-docs/guided-learning/gettingstarted.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by LisandroSu** [comment]
Hola, @todobien777 : 

Gracias por sus comentarios. 

Escalaremos su propuesta.

Atentamente, 
Equipo internacional de Microsoft Docs
